name: Deploy Docker Images

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: asymworks/jadetree-frontend
        tag_with_ref: true
        tags: 0-alpha,0.9-alpha
